my_library/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add_cart/<int:id>/', views.add_cart, name='add_cart'),
    path('remove/<int:book_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:book_id>/', views.full_remove, name='full_remove'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
]

my_library/my_library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mylibrary.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_library/mylibrary/urls.py
from django.urls import path

from mylibrary.views import *

app_name = 'mylibrary'

urlpatterns = [
    path('', home, name='home'),
    path('book/<int:id>/', detail_view, name='detail'),
    path('add_book/', add_book, name='add_book'),
    path('update/<int:id>/', update_book, name='update'),
    path('delete/<int:id>/', delete_book, name='delete'),
    path('signup/', signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('add_patron/', add_patrons, name='add_patron'),
    path('all_patrons/', all_patrons, name='all_patrons'),
    path('update_patron/<int:id>/', update_patron, name='update_patron'),
    path('delete_patron/<int:id>/', delete_patron, name='delete_patron'),
    path('newspaper/', news_paper, name='newspaper'),
    path('program/<int:id>/', programmes, name='program'),
    path('category/', all_book_category, name='all_book_category'),
    path('category/<slug:c_slug>/', all_book_category, name='books_by_category'),

]

my_library/search_app/urls.py
from django.urls import path

from mylibrary.views import *
from search_app import views

app_name = 'search_app'

urlpatterns = [
    path('', views.search_result, name='search'),
    path('patron/', views.patrons, name='patron'),
    path('superuser/', superuser, name='superuser'),
    path('add_notification/', add_notifications, name='add_notify'),
    path('download/<int:notification_id>/', download_card, name='download_page'),
    path('download/<int:notification_id>/', download_card, name='download'),
    path('update_notification/<int:id>/', update_notify, name='update_notify'),
    path('update_news/<int:id>/', update_news, name='update_news'),
    path('delete_notification/<int:id>/', delete_notify, name='delete_notify'),
    path('issue_patron/<int:id>/', issue_patron, name='issue_patron'),
    path('return_patron/<int:id>/', return_patron, name='return_patron'),
    path('renew_patron/<int:id>/', renew_patron, name='renew_patron'),
    path('return_all_books/<int:id>/', return_all_books, name='return_all_books'),
    path('renew_all_books/<int:id>/', renew_all_books, name='renew_all_books'),
    path('pay_all_fine/<int:id>/', pay_all_fine, name='pay_all_fine'),
    path('pay_fine/<int:id>/', pay_fine, name='pay_fine'),
    path('all_history/', all_history, name='all_history'),
    path('history/', history, name='history'),
    path('add_category/', add_category, name='add_category'),
    path('add_language/', add_language, name='add_language'),
    path('add_newspaper/', add_newspaper, name='add_newspaper'),
    path('delete_category/<int:id>/', delete_category, name="delete_category"),
    path('delete_language/<int:id>/', delete_language, name="delete_language"),
    path('delete_newspaper/<int:id>/', delete_newspaper, name="delete_newspaper"),
    path('all_programmes/', all_programmes, name='all_programmes'),
    path('profile/<int:id>/', profile, name='profile'),
    path('language/<slug:l_slug>/', all_book_language, name='books_by_language'),
    path('language/', all_book_language, name='all_book_language'),

]

my_library/cart/models.py
from django.db import models
from mylibrary.models import Book_details


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    book = models.ForeignKey(Book_details, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.book.price * self.quantity

    def __str__(self):
        return '{}'.format(self.book)

my_library/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from mylibrary.models import Book_details
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, id):
    book = Book_details.objects.get(id=id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(book=book, cart=cart)
        if cart_item.quantity < cart_item.book.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            book=book,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_details')


def cart_details(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.book.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, book_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    book = get_object_or_404(Book_details, id=book_id)
    cart_item = CartItem.objects.get(book=book, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')


def full_remove(request, book_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    book = get_object_or_404(Book_details, id=book_id)
    cart_item = CartItem.objects.get(book=book, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_details')


def clear_cart(request):
    # Clear the cart items and set the amount to zero
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cart_items = CartItem.objects.filter(cart=cart)
    cart_items.delete()

    # Redirect back to the cart details page
    return redirect('cart:cart_details')

my_library/templates/all_patrons.html
{% extends 'base.html' %}
{% block body %}
<title>{% block title %}all patron{% endblock %}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@2.0.7/css/boxicons.min.css">
<style>
 body{
background: #eff3f6;
}
.thumb-lg {
height: 88px;
width: 88px;
}
.card {
border: none;
box-shadow: 1px 0px 20px rgba(0, 0, 0, 0.05);
}
.m-b-30 {
margin-bottom: 30px;
}
.social-links li a {
-webkit-border-radius: 50%;
background: #fcfdfd;
border-radius: 50%;
color: #9f9f9f;
display: inline-block;
height: 30px;
line-height: 30px;
text-align: center;
width: 30px;
}

</style>
<br><br>
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12 ">
            <div>
                <form action="{% url 'search_app:patron' %}" class="search-bar">
                    <input aria-label="Search" class="" name="q" placeholder="Search {{ patron_count }} patrons..."
                           type="search">
                    <button class="btn btn-light" type="submit" >
                        <i class="fa-solid fa-magnifying-glass fa-xl fa-beat"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div><br><br>
<div class="col-lg-12">
    <div class="row">
        {% for i in patron %}
        <div class="col-lg-3 p-1">
            <div class="card">
                <div class="card-body text-center">
                    <div class="media">
                        <img class="rounded-circle img-thumbnail thumb-lg"
                             src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="Generic placeholder image"/>
                        <div class="media-body"><br>
                            <h4 class="mt-0 font-18 mb-1 text-uppercase"><b>{{i.name}}</b></h4>
                            <p class="text-muted font-16"><b>{{i.card_no}}</b></p>
                            <div>
                                <a class="btn btn-info" href="{% url 'search_app:profile' i.id %}">USER</a>
                                <a class="btn btn-dark" href="{% url 'search_app:issue_patron' i.id %}">ISSUE</a>
                                <a class="btn btn-success" href="{% url 'search_app:return_patron' i.id %}">RETURN</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

my_library/templates/base.html
<html>
<head>
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>
{% include 'nav.html' %}
{% block body %}
{% endblock %}
{% block metadescription %}
{% endblock %}
{% include 'footer.html' %}
</body>
</html>

my_library/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<title>{% block title %}details{% endblock %}</title>
<style>
    .color-1 { background-color: #FF3366; }
    .color-2 { background-color: #FF9900; }
    .color-3 { background-color: #FFCC00; }
    .color-4 { background-color: #66CC00; }
    .color-5 { background-color: #00CCCC; }
    .color-6 { background-color: #3399FF; }
    .color-7 { background-color: #9933FF; }
    .color-8 { background-color: #FF33CC; }
    .color-9 { background-color: #FF6666; }
    .color-10 { background-color: #FFCC99; }
    .color-11 { background-color: #99CC99; }
    .color-12 { background-color: #66CCCC; }
</style>&nbsp;
<div class="col-md-12">
    <div class="card l-bg-orange col-md-12 text-center">
    <div class="row">
        <div class="col-md-12  bg-dark"><br>
            <h4 class="card-text text-uppercase text-center ">
                <b>{{book.name}} ( {{ book.primary_number }} )</b>
            </h4><br>
        </div>
        <div class="col-md-2 text-center">
            <img src="https://assets.stickpng.com/images/580b585b2edbce24c47b276e.png" style="width: 250px; border-radius: 20px;">
        </div>
        <div class="col-md-6"><br>
            <table width="100%" class="text-center">
                <tr>
                    <td>
                        <p class="card-text text-uppercase"><b>Author:</b></p>
                    </td>
                    <td>
                        <p class="card-text text-uppercase">{{book.author}}</p>
                    </td>
                </tr>
                <tr>
                    <td><br>
                        <p class="card-text text-uppercase"><b>Description:</b></p>
                    </td>
                    <td><br>
                        <p class="card-text text-uppercase">{{book.desc}}</p>
                    </td>
                </tr>
                <tr>
                    <td><br>
                        <p class="card-text text-uppercase"><b>Category:</b></p>
                    </td>
                    <td><br>
                        <p class="card-text text-uppercase">{{book.category}}</p>
                    </td>
                </tr>
                <tr>
                    <td><br>
                        <p class="card-text text-uppercase"><b>Stock:</b></p>
                    </td>
                    <td><br>
                        <p class="card-text text-uppercase">{{book.stock}}</p>
                    </td>
                </tr>
                <tr>
                    <td><br>
                        <p class="card-text text-uppercase"><b>Price:</b></p>
                    </td>
                    <td><br>
                        <p class="card-text text-uppercase">{{book.price}}</p>
                    </td>
                </tr>
                <tr>
                    <td><br>
                        <p class="card-text text-uppercase"><b>Language:</b></p>
                    </td>
                    <td><br>
                        <p class="card-text text-uppercase">{{book.lang}}  </p>
                    </td>
                </tr>
            </table>

        </div>
        <div class="col-md-4 text-center"><br><br>
            <a href="/" class="btn btn-lg btn-success">
                READ <i class="text-center fa fa-book fa-solid "></i>
            </a>
            <a href="/" download class="btn btn-lg btn-info text-white ">
                HERE <i class="fas fa-download "></i>
            </a><br><br>
            <a href="{% url 'cart:add_cart' book.id %}" class="btn btn-secondary btn-lg form-control">
                ORDER NOW <i class="text-center fa-solid fa-cart-plus fa-solid "></i>
            </a>
            <br><br>
            <a href="{% url 'mylibrary:delete' book.id %}" class="btn btn-lg btn-danger  ">
                DELETE <i class="fa-solid fa-trash"></i>
            </a>
            <a href="{% url 'mylibrary:update' book.id %}"  class="btn btn-lg btn-dark text-light">
                UPDATE <i class="fa-brands fa-openid"></i>
            </a>
        </div>
    </div><br><br>
</div>
</div>
{% endblock %}

my_library/templates/download.html
{% load static %}
<html lang="en">
<body>
    <div class="container">
        <div class="row">
            <div class="card col-md-12 ">
                <br>
                <div class="card">
                    <br>
                    <h4><b>{{ msg.name }}</b></h4>
                    <br>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card-content">
                                <h4 class="card-title">On</h4>
                                <p class="text-uppercase">{{ msg.on }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Location</h4>
                                <p class="text-uppercase">{{ msg.location }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Inauguration</h4>
                                <p class="text-uppercase">{{ msg.inauguration }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Welcome speech</h4>
                                <p class="text-uppercase">{{ msg.welcome_speech }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Presidential Speech</h4>
                                <p class="text-uppercase">{{ msg.presidential_speech }}</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card-content">
                                <h4 class="card-title">Greetings</h4>
                                <p class="text-uppercase">{{ msg.greetings }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Special Speech</h4>
                                <p class="text-uppercase">{{ msg.special_speech }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Speech</h4>
                                <p class="text-uppercase">{{ msg.speech }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Song</h4>
                                <p class="text-uppercase">{{ msg.song }}</p>
                            </div>
                            <div class="card-content">
                                <h4 class="card-title">Vote of Thanks</h4>
                                <p class="text-uppercase">{{ msg.vote_of_thanks }}</p>
                            </div>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/script.js'%}"></script>
</body>
</html>

my_library/templates/return_book.html
{% extends 'base.html' %}

<title>{% block title %}Return Book{% endblock %}</title>

{% block body %}

{% load custom_filters %}
<div class="button-group text-center">
    <div class="col-md-11">
        <div class="row">
            <div class="col-md-2">
                <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Image"
                     class="img-fluid" style="height: 200px; width: 300px; border-radius: 200px;">
            </div>
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-8 offset-md-3">
                        <h3 class="text-center" style="padding: 10px 100px;">
                            <b class="text-white text-uppercase">Return Books</b>
                        </h3>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="primary_number">Enter Book Primary Number:</label>
                                <select name="primary_number" class="form-control form-select" id="primary_number" required>
                                    <option value="">_________</option>
                                    {% for book in cbook %}
                                    {% if book.is_issued %}
                                        {% for returned_book in returned_books %}
                                            {% if returned_book.book == book and returned_book.patron == patron %}
                                                <option value="{{ returned_book.book.primary_number }}">
                                                    {{ returned_book.book.name }} ({{ returned_book.book.primary_number }}) issued by {{ returned_book.patron.name }}
                                                </option>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary">RETURN BOOK</button>
                            <br>
                            {% for message in messages %}
                                <div class="alert alert-info">{{ message }}</div>
                            {% endfor %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="row">
            <div class="card col-md-2 text-center text-uppercase"><br>
                <h3><b>{{ patron.name }}</b></h3>
                <h6>Card No:</h6>
                <h5 style="color: #000;">{{ patron.card_no }}</h5>
                <h6>Phone Number:</h6>
                <h5 style="color: #000;">{{ patron.phone }}</h5>
                <h6>Email:</h6>
                <h5 style="color: #000;" class="text-lowercase">{{ patron.gmail }}</h5>
            </div>
            <div class="col-md-1"></div>
            <div class="card col-md-8">
                {% if patron %}
                <table class="table">
                    <thead>
                    <tr class="text-uppercase text-center">
                       <th><b>Book Name</b></th>
                        <th><b>Issued To</b></th>
                        <th><b>ISSUE DATE</b></th>
                        <th><b>RETURN DATE</b></th>
                        <th><b>ACTION</b></th>
                    </tr>
                    </thead>
                    <tbody class="text-uppercase text-center">
                    {% for book in returned_books %}
                    <tr>
                        <td>{{ book.book }}</td>
                        <td>{{ book.patron }}</td>
                        <td>{{ book.issue_date }}</td>
                        <td>{{ book.return_date }}</td>
                        <td>
                            {% if book.renewal_count >= 2 %}
                                <a href="{% url 'search_app:issue_patron' patron.id %}" class="btn btn-sm btn-warning">ISSUE</a>
                            {% else %}
                                <a href="{% url 'search_app:renew_patron' book.id %}" class="btn btn-sm btn-dark">RENEW</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    </tbody>
                </table>
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="text-center">
                                <a href="{% url 'search_app:return_all_books' patron.id %}" class="btn btn-lg btn-danger">Return All Books</a>
                                {% if patron.fine > 0 %}
                                <a href="{% url 'search_app:pay_all_fine' patron.id %}" class="btn btn-lg btn-warning">Pay All Fine</a>
                                {% else %}
                                <a href="{% url 'search_app:renew_all_books' patron.id %}" class="btn btn-lg btn-success">Renew All Books</a>
                                <a href="{% url 'search_app:issue_patron' patron.id %}" class="btn btn-lg btn-primary">Issue Book</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                {% else %}
                <p>No books Returned for this patron.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="col-md-12">
    <div class="row">
        <div class="card col-md-2"><br>
             <h5 class="text-danger text-center">
                 <b>FINE BALANCE:<br><i class="fa fa-rupee"></i> {{ patron.fine }}</b><br>
                        {% if patron %}
                 <b class="text-success" >FINE PAID YET:<br> <i class="fa fa-rupee"></i>{{ patron.paid }}</b>
                        {% endif %}


            </h5>
        </div>
        <div class="col-md-1"></div>
        <div class="card col-md-8">
            <form method="post" class="text-center" action="{% url 'search_app:pay_fine' patron.id %}">
                {% csrf_token %}
                <br>
                <div class="form-group">
                    <label for="amount_paid" class="text-center text-uppercase">
                        <h4><b>Enter Your amount</b></h4>
                    </label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Now your fine:</span>
                        </div>
                        <input type="number" class="form-control" id="amount_paid"
                               name="amount_paid" placeholder="{{ patron.balance }}" value="{{ patron.fine }}">
                        <button class="btn btn-success" type="submit">PAY</button>
                    </div>
                </div>
                <br>
            </form>
        </div>
    </div>
</div><br>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.min.js"></script>
{% endblock %}

my_library/templates/search.html
{% extends 'base.html' %}
{% block body %}
<title>{% block title %}search{% endblock %}</title>
{% if book_s %}
<style>
    {
        % for book in book_s %
    }

    .book-color- {
            {
            forloop.counter
        }
    }

        {
        background-color: {
            % cycle '#FF3366' '#FF9900' '#FFCC00' '#66CC00' '#00CCCC' '#3399FF' '#9933FF' '#FF33CC' '#FF6666' '#FFCC99' '#99CC99' '#66CCCC' %
        }

        ;
    }

        {
        % endfor %
    }

    @media screen and (max-width: 600px) {
        .col-lg-2 {
            flex: 0 0 100%;
            /* Force each column to occupy the full width */
            max-width: 50%;
        }

        .book_1 {
            max-width: 40%;
        }

        .book_2 {
            max-width: 58%;
        }
    }
</style>
<br>
<div>
    <h3 class="text-center my_search_text text-secondary">YOU HAVE SEARCHED FOR : <b>"{{query}}"</b></h3>
</div>
<br><br>
<div class="col-md-12">
    <div class="row">
        {% for book in book_s %}
        <div class=" col-md-1 book_1"><br>
            <div style="border-radius: 10px;" class=" text-center radius:20px book-color-{{ forloop.counter }}">
                <b>{{book.primary_number}}</b>
            </div>
            <div class="text-center">
                <img alt="{{ book.name }}" class="card-img"
                    src="https://creazilla-store.fra1.digitaloceanspaces.com/emojis/48096/orange-book-emoji-clipart-md.png"
                    style="border-radius: 20px; height:200px; width: 180px;">
            </div>
        </div>
        <a class="text-dark" href="{% url 'mylibrary:detail' book.id %}" style="text-decoration: none;">
            <div class="card col-md-2 text-center book_2">
                <div class="card-body">
                    <h6 class="card-title text-uppercase"><b>{{ book.name }}</b></h6>
                    <p class="card-text text-uppercase">({{ book.author }} )</p>
                    <p class="card-text text-uppercase text-left">CATEGORY: {{ book.category.name }} </p>
                    <p class="card-text text-uppercase text-left">LANGUAGE: {{ book.lang }}</p>
                    <p class="card-text text-uppercase text-left">PRICE: <i class="fa fa-rupee"></i> {{ book.price }}
                    </p>
                    <a class="btn btn-primary" href="{% url 'mylibrary:detail' book.id %}">
                        More <i class="fa-sharp fa-solid fa-angles-right"></i>
                    </a>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% elif s_patron %}
<style>
    {
        % for book in book %
    }

    .book-color- {
            {
            forloop.counter
        }
    }

        {
        background-color: {
            % cycle '#FF3366' '#FF9900' '#FFCC00' '#66CC00' '#00CCCC' '#3399FF' '#9933FF' '#FF33CC' '#FF6666' '#FFCC99' '#99CC99' '#66CCCC' %
        }

        ;
    }

        {
        % endfor %
    }

    body {
        background: #eff3f6;
    }

    .thumb-lg {
        height: 88px;
        width: 88px;
    }

    .card {
        border: none;
        box-shadow: 1px 0px 20px rgba(0, 0, 0, 0.05);
    }

    .m-b-30 {
        margin-bottom: 30px;
    }

    .social-links li a {
        -webkit-border-radius: 50%;
        background: #fcfdfd;
        border-radius: 50%;
        color: #9f9f9f;
        display: inline-block;
        height: 30px;
        line-height: 30px;
        text-align: center;
        width: 30px;
    }
</style>
<br>
<div>
    <h3 class="text-center my_search_text text-secondary">YOU HAVE SEARCHED FOR : <b>"{{query}}"</b></h3>
</div>
<br><br>
<div class="col-lg-12">
    <div class="row">
        {% for i in s_patron %}
        <div class="col-lg-3 p-1">
            <div class="card">
                <div class="card-body text-center">
                    <div class="media">
                        <img class="rounded-circle img-thumbnail thumb-lg"
                            src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="Generic placeholder image" />
                        <div class="media-body"><br>
                            <h4 class="mt-0 font-18 mb-1 text-uppercase"><b>{{i.name}}</b></h4>
                            <p class="text-muted font-16"><b>{{i.card_no}}</b></p>
                            <div>
                                <a class="btn btn-info" href="{% url 'search_app:profile' i.id %}">USER</a>
                                <a class="btn btn-dark" href="{% url 'search_app:issue_patron' i.id %}">ISSUE</a>
                                <a class="btn btn-success" href="{% url 'search_app:return_patron' i.id %}">RETURN</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<br><br><br><br>
<h1 class="text-uppercase text-dark text-center">"{{query}}" not available here search more.</h1>
<div class="just__center">
    <button class="btn btn-primary"><a class="style__102 search__home" href="{% url 'mylibrary:home' %}">Home</a></button>
</div>
<br><br><br><br>
{% endif %}
{% endblock %}